---
- hosts: ditochat
  vars:
    release_path: /home/negreiros/ditochat_public

  tasks:
    - name: Clona o repositório
      git:
        repo: ssh://git@github.com/GabrielNegreirosLima/dito-chat.git
        accept_hostkey: yes
        key_file: /home/negreiros/.ssh/id_rsa
        version: scripts-cd
        dest: "{{ release_path }}"
